# docker-compose.yml
# version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5001"
    environment:
      - PORT=5001

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    ports:
      - "3000:3000"