# .github/workflows/main.yml

name: CI/CD Inventaris App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-analyze-push:
    name: Build, Test, Analyze & Push
    runs-on: ubuntu-latest # Menjalankan pipeline di mesin virtual Ubuntu

    steps:
      # Langkah 1: Mengambil kode dari repositori Anda
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Diperlukan untuk analisis SonarCloud

      # Langkah 2: Menyiapkan lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Langkah 3: Menginstal dependensi dari requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Langkah 4: Menjalankan unit test dengan PyTest
      - name: Run Unit Tests
        run: python -m pytest src/test_app.py

      # Langkah 5: Analisis kode dengan SonarCloud
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Langkah 6: Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 7: Build dan Push image Docker ke Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proyek-inventaris:latest